(add-to-list 'auto-mode-alist '("\\.json$" . javascript-mode))
(setq c-default-style "gnu")
(if (equal major-mode "php-mode")
	(c-set-style "gnu"))
(setq-default indent-tabs-mode t)
(setq-default tab-width 4)
(setq-default css-indent-offset 4)
(setq-default c-basic-offset 4)
(setq js-indent-level 4)